/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CreateUpdateLogsServlet */

#ifndef _Included_CreateUpdateLogsServlet
#define _Included_CreateUpdateLogsServlet
#ifdef __cplusplus
extern "C" {
#endif
#undef CreateUpdateLogsServlet_serialVersionUID
#define CreateUpdateLogsServlet_serialVersionUID 1i64
#undef CreateUpdateLogsServlet_serialVersionUID
#define CreateUpdateLogsServlet_serialVersionUID 1i64
/*
 * Class:     CreateUpdateLogsServlet
 * Method:    readSystemLog
 * Signature: (Ljava/lang/String;)[LSystemLog;
 */
JNIEXPORT jobjectArray JNICALL Java_CreateUpdateLogsServlet_readSystemLog
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
