/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemLogReader */

#ifndef _Included_SystemLogReader
#define _Included_SystemLogReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SystemLogReader
 * Method:    readSystemLog
 * Signature: (Ljava/io/PrintWriter;)V
 */
JNIEXPORT void JNICALL Java_SystemLogReader_readSystemLog
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
