/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    readSystemLog
 * Signature: (Ljava/lang/String;)[LSystemLog;
 */
JNIEXPORT jobjectArray JNICALL Java_Test_readSystemLog
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
